server:
  port: 7001

spring:
  application:
    name: edufleet
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use "update" only for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      springframework:
        security=DEBUG:
        #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Shows SQL bind params

