server:
  port: 7001

spring:
  application:
    name: edufleet
  datasource:
    url: jdbc:postgresql://localhost:5432/db_edufleet
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use "update" only for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9df3ea609f6e35
    password: 3695aebfe83d05
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      springframework:
        security=DEBUG:
        #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Shows SQL bind params

