server:
  port: 7001

spring:
  config:
    import:
      optional:file:.env[.properties]
  application:
    name: edufleet
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use "update" only for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: 2525
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      springframework:
        security=DEBUG:
        #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Shows SQL bind params

