server:
  port: 7001

spring:
  application:
    name: edufleet
  datasource:
    url: jdbc:postgresql://localhost:5432/db_edufleet
    username: postgres
    password: 7299
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use "update" only for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs

    
logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      springframework:
        security=DEBUG:
        #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Shows SQL bind params

